// user actions
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

// group actions
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';
export const CREATE_GROUP_SUCCESS_MESSAGE = 'CREATE_GROUP_SUCCESS_MESSAGE';

// password actions
export const PASSWORD_EMAIL_LINK_SUCCESS = 'PASSWORD_EMAIL_LINK_SUCCESS';
export const PASSWORD_EMAIL_LINK_FAILURE = 'PASSWORD_EMAIL_LINK_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

