// user actions
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const AUTH_IS_LOADING = 'AUTH_IS_LOADING';

// group actions
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';
export const CREATE_GROUP_SUCCESS_MESSAGE = 'CREATE_GROUP_SUCCESS_MESSAGE';
export const FETCH_USER_GROUPS_SUCCESS = 'FETCH_USER_GROUPS_SUCCESS';
export const FETCH_USER_GROUPS_ERROR = 'FETCH_USER_GROUPS_ERROR';
export const FETCH_GROUP_USERS_SUCCESS = 'FETCH_GROUP_USERS_SUCCESS';
export const FETCH_GROUP_USERS_FAILURE = 'FETCH_GROUP_USERS_FAILURE';
export const GROUP_IS_LOADING = 'GROUP_IS_LOADING';
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const EXIT_GROUP = 'EXIT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const REMOVE_GROUP_MEMBER = 'REMOVE_GROUP_MEMBER';


// password actions
export const PASSWORD_EMAIL_LINK_SUCCESS = 'PASSWORD_EMAIL_LINK_SUCCESS';
export const PASSWORD_EMAIL_LINK_FAILURE = 'PASSWORD_EMAIL_LINK_FAILURE';
export const PASSWORD_IS_LOADING = 'PASSWORD_IS_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// message actions
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_FAILURE = 'POST_MESSAGE_FAILURE';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const MESSAGE_IS_LOADING = 'MESSAGE_IS_LOADING';
export const POST_MESSAGE = 'POST_MESSAGE';

