// user actions
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const AUTH_IS_LOADING = 'AUTH_IS_LOADING';

// group actions
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const FETCH_USER_GROUPS_SUCCESS = 'FETCH_USER_GROUPS_SUCCESS';
export const FETCH_GROUP_USERS_SUCCESS = 'FETCH_GROUP_USERS_SUCCESS';
export const GROUP_IS_LOADING = 'GROUP_IS_LOADING';
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const EXIT_GROUP = 'EXIT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const REMOVE_GROUP_MEMBER = 'REMOVE_GROUP_MEMBER';


// password actions
export const PASSWORD_IS_LOADING = 'PASSWORD_IS_LOADING';


// message actions
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const MESSAGE_IS_LOADING = 'MESSAGE_IS_LOADING';
export const POST_MESSAGE = 'POST_MESSAGE';

